name: skill_swap_platform
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  http: 

  shared_preferences: ^2.3.0
  provider: ^6.1.0
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7
  flutter_slidable:
  lottie:
  flutter_rating_bar: ^4.0.1
  pull_to_refresh: ^2.0.0
  percent_indicator: ^4.2.3
  material_dialogs: ^1.1.5
  glassmorphism: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ 
  # Use AppColors from theme.dart, and constants.AppColors for the other if needed 